language: node_js
sudo: false
cache:
  directories:
    - node_modules
node_js:
  - "6.6.0"
env:
  - CXX=g++-4.8
  - REDIS_ENDPOINT=redis://localhost:6379
services:
  - redis-server
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8