language: node_js
sudo: false
cache:
  directories:
    - node_modules
node_js:
  - "6.11.1"
  - "7"
  - "8"
  - "node"
notifications:
  email:
    - backstage1@corp.globo.com
  slack:
    secure: HerVthx+d5fELXWoUjmK896uPPbkKCyFKjtYiSn3h88UbECPrAwRltZhuxD7t+NGt4fcCD/aiEdem5cBTKTNZxPCNAjvBZMx7REnk0QeHL9QPardS1BA1a+o02ne25vJcd7indc7UqscUmfvEvFugXEhiHaf8Nf3e0OYk5oCx0I=
env:
  - CXX=g++-4.8 REDIS_ENDPOINT=redis://localhost:6379/0
services:
  - redis-server
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
script: make test
after_success:
  npm run send_cover
