 version: '2'
 services:
   web:
     image: globobackstage/functions
     ports:
      - "8100:8100"
     depends_on:
      - redis
     environment:
       REDIS_ENDPOINT: redis://redis:6379/0
   redis:
     image: redis